### ISSUE TITLE
AssertionError: "undefined" === "function"

### ISSUE THREAD

**Issue by maxfriedmann** [kadirahq/meteord#6]
Which tag version currently works with Meteor 1.4.0.1 together? I can't get any container started, they all have node 0.10.x installed :(

**Comment by jbg77** [comment]
Try this: [hub.docker.com/r/ulexus/meteor/](https://hub.docker.com/r/ulexus/meteor/)

**Comment by maxfriedmann** [comment]
https://github.com/CyCoreSystems/docker-meteor/issues/21 ;-)

But abernix/meteord:base works just fine!

**Comment by rushi216** [comment]
I think they have committed node 4.4.7 to github repo, but their build is failing, so docker image(meteorhacks/meteord) is still giving old node version

**Comment by bigdoods** [comment]
I have same issue when trying to run docker container with bundled meteor (v1.4.1.2) [hello-world](https://www.meteor.com/tutorials/blaze/creating-an-app) app.

I am putting tar.gz file in bundle_dir/bundle folder and I am using meteorhacks/meteord:base as my base docker image. 

>    docker run -d \
>     -e ROOT_URL=http://localhost:3000/ \
>     -e MONGO_URL=http://localhost:3001/ \
>     -v ~/yano/simple-todos/bundle_dir/bundle:/bundle \
>     -p 8080:80 \
>     meteorhacks/meteord:base

@maxfriedmann did you get sorted?

**Comment by maxfriedmann** [comment]
@bigdoods, no, I haven't had the time to sort it out. Am using abernix/meteord:base since then which works like a charm.

**Comment by bigdoods** [comment]
Ok thanks. I will give it a try.
